"""
Midscene Python - Shared Module
"""

from .logger import get_debug, set_log_level, MidsceneLogger
from .env import (
    IModelConfig,
    ModelConfigManager,
    global_model_config_manager,
    get_env_value,
    get_env_bool,
    get_env_int,
    get_env_float,
    parse_model_config_for_intent,
    model_family_to_vl_config,
    MIDSCENE_MODEL_NAME,
    MIDSCENE_MODEL_API_KEY,
    MIDSCENE_MODEL_BASE_URL,
    MIDSCENE_MODEL_HTTP_PROXY,
    MIDSCENE_MODEL_FAMILY,
    MIDSCENE_MODEL_SKIP_CERT_VERIFICATION,
    MIDSCENE_REPLANNING_CYCLE_LIMIT,
)
from .utils import (
    uuid,
    generate_hash_id,
    assert_condition,
    replace_illegal_path_chars,
    sleep,
    async_sleep,
)
from .types import (
    Rect,
    Size,
    Point,
    LocateResultElement,
    UIContext,
    AIUsageInfo,
    DetailedLocateParam,
    PlanningAction,
    PlanningAIResponse,
    ServiceDump,
    ServiceError,
    LocateResultWithDump,
    ExecutionRecorderItem,
    ExecutionTaskStatus,
    ExecutionTask,
    ExecutionDump,
    GroupedActionDump,
    DeviceAction,
    AgentOpt,
)
from .img import (
    parse_base64,
    create_img_base64_by_format,
    base64_to_pil_image,
    pil_image_to_base64,
    get_image_info,
    image_info_of_base64,
    resize_image,
    resize_img_base64,
    padding_to_match_block,
    padding_to_match_block_by_base64,
    crop_by_rect,
    composite_element_info_img,
)

__all__ = [
    # Logger
    'get_debug',
    'set_log_level',
    'MidsceneLogger',
    # Env
    'IModelConfig',
    'ModelConfigManager',
    'global_model_config_manager',
    'get_env_value',
    'get_env_bool',
    'get_env_int',
    'get_env_float',
    'parse_model_config_for_intent',
    'model_family_to_vl_config',
    'MIDSCENE_MODEL_NAME',
    'MIDSCENE_MODEL_API_KEY',
    'MIDSCENE_MODEL_BASE_URL',
    'MIDSCENE_MODEL_HTTP_PROXY',
    'MIDSCENE_MODEL_FAMILY',
    'MIDSCENE_MODEL_SKIP_CERT_VERIFICATION',
    'MIDSCENE_REPLANNING_CYCLE_LIMIT',
    # Utils
    'uuid',
    'generate_hash_id',
    'assert_condition',
    'replace_illegal_path_chars',
    'sleep',
    'async_sleep',
    # Types
    'Rect',
    'Size',
    'Point',
    'LocateResultElement',
    'UIContext',
    'AIUsageInfo',
    'DetailedLocateParam',
    'PlanningAction',
    'PlanningAIResponse',
    'ServiceDump',
    'ServiceError',
    'LocateResultWithDump',
    'ExecutionRecorderItem',
    'ExecutionTaskStatus',
    'ExecutionTask',
    'ExecutionDump',
    'GroupedActionDump',
    'DeviceAction',
    'AgentOpt',
    # Img
    'parse_base64',
    'create_img_base64_by_format',
    'base64_to_pil_image',
    'pil_image_to_base64',
    'get_image_info',
    'image_info_of_base64',
    'resize_image',
    'resize_img_base64',
    'padding_to_match_block',
    'padding_to_match_block_by_base64',
    'crop_by_rect',
    'composite_element_info_img',
]
