"""
共享模块
Shared module for midscene
"""
from .utils import (
    uuid,
    generate_hash_id,
    assert_condition,
    if_in_browser,
    if_in_node,
    escape_script_tag,
    anti_escape_script_tag,
    replace_illegal_path_chars_and_space,
    sleep_ms,
)

from .logger import (
    get_debug,
    enable_debug,
    disable_debug,
    cleanup_log_streams,
)

from .env import (
    MIDSCENE_MODEL_NAME,
    MIDSCENE_MODEL_API_KEY,
    MIDSCENE_MODEL_BASE_URL,
    MIDSCENE_MODEL_FAMILY,
    MIDSCENE_MODEL_HTTP_PROXY,
    MIDSCENE_MODEL_TIMEOUT,
    MIDSCENE_MODEL_TEMPERATURE,
    MIDSCENE_REPLANNING_CYCLE_LIMIT,
    MIDSCENE_FORCE_DEEP_THINK,
    INTENT_DEFAULT,
    INTENT_INSIGHT,
    INTENT_PLANNING,
    VL_MODE_VALUES,
    ModelConfig,
    ModelConfigManager,
    get_env_value,
    get_env_bool,
    get_env_int,
    get_global_model_config_manager,
    set_global_model_config_manager,
)

from .types import (
    Point,
    Size,
    Rect,
    LocateResultElement,
    UIContext,
    PlanningAction,
    PlanningAIResponse,
    AIUsageInfo,
    ServiceAction,
    ServiceDump,
    ServiceError,
    LocateResult,
    LocateResultWithDump,
    DetailedLocateParam,
    ExecutionTask,
    ExecutionDump,
    ActionTapParam,
    ActionInputParam,
    ActionScrollParam,
    ActionKeyboardPressParam,
    ActionAssertParam,
)

from .img import (
    base64_to_bytes,
    bytes_to_base64,
    parse_base64,
    image_info_of_base64,
    resize_img_base64,
    create_img_base64_by_format,
    padding_to_match_block_by_base64,
    crop_by_rect,
)

__all__ = [
    # utils
    "uuid",
    "generate_hash_id",
    "assert_condition",
    "if_in_browser",
    "if_in_node",
    "escape_script_tag",
    "anti_escape_script_tag",
    "replace_illegal_path_chars_and_space",
    "sleep_ms",
    # logger
    "get_debug",
    "enable_debug",
    "disable_debug",
    "cleanup_log_streams",
    # env
    "MIDSCENE_MODEL_NAME",
    "MIDSCENE_MODEL_API_KEY",
    "MIDSCENE_MODEL_BASE_URL",
    "MIDSCENE_MODEL_FAMILY",
    "MIDSCENE_MODEL_HTTP_PROXY",
    "MIDSCENE_MODEL_TIMEOUT",
    "MIDSCENE_MODEL_TEMPERATURE",
    "MIDSCENE_REPLANNING_CYCLE_LIMIT",
    "MIDSCENE_FORCE_DEEP_THINK",
    "INTENT_DEFAULT",
    "INTENT_INSIGHT",
    "INTENT_PLANNING",
    "VL_MODE_VALUES",
    "ModelConfig",
    "ModelConfigManager",
    "get_env_value",
    "get_env_bool",
    "get_env_int",
    "get_global_model_config_manager",
    "set_global_model_config_manager",
    # types
    "Point",
    "Size",
    "Rect",
    "LocateResultElement",
    "UIContext",
    "PlanningAction",
    "PlanningAIResponse",
    "AIUsageInfo",
    "ServiceAction",
    "ServiceDump",
    "ServiceError",
    "LocateResult",
    "LocateResultWithDump",
    "DetailedLocateParam",
    "ExecutionTask",
    "ExecutionDump",
    "ActionTapParam",
    "ActionInputParam",
    "ActionScrollParam",
    "ActionKeyboardPressParam",
    "ActionAssertParam",
    # img
    "base64_to_bytes",
    "bytes_to_base64",
    "parse_base64",
    "image_info_of_base64",
    "resize_img_base64",
    "create_img_base64_by_format",
    "padding_to_match_block_by_base64",
    "crop_by_rect",
]
