"""常量定义"""
# 网络超时配置（毫秒）
DEFAULT_WAIT_FOR_NAVIGATION_TIMEOUT = 10000
DEFAULT_WAIT_FOR_NETWORK_IDLE_TIMEOUT = 5000
DEFAULT_WAIT_FOR_NETWORK_IDLE_CONCURRENCY = 2
# 规划循环限制
DEFAULT_REPLANNING_CYCLE_LIMIT = 20
# 对话历史中最大截图数量
DEFAULT_MAX_IMAGES_IN_HISTORY = 2
# 最大错误重试次数
MAX_ERROR_COUNT_IN_PLANNING_LOOP = 5
# 环境变量名
ENV_MODEL_NAME = "MIDSCENE_MODEL_NAME"
ENV_MODEL_BASE_URL = "MIDSCENE_MODEL_BASE_URL"
ENV_MODEL_API_KEY = "MIDSCENE_MODEL_API_KEY"
ENV_MODEL_FAMILY = "MIDSCENE_MODEL_FAMILY"
ENV_HTTP_PROXY = "MIDSCENE_MODEL_HTTP_PROXY"
ENV_SOCKS_PROXY = "MIDSCENE_MODEL_SOCKS_PROXY"
ENV_SKIP_CERT_VERIFICATION = "MIDSCENE_MODEL_SKIP_CERT_VERIFICATION"
ENV_MAX_IMAGES_IN_HISTORY = "MIDSCENE_MAX_IMAGES_IN_HISTORY"
ENV_REPLANNING_CYCLE_LIMIT = "MIDSCENE_REPLANNING_CYCLE_LIMIT"
ENV_MODEL_TIMEOUT = "MIDSCENE_MODEL_TIMEOUT"
ENV_MODEL_TEMPERATURE = "MIDSCENE_MODEL_TEMPERATURE"
