# -*- coding: utf-8 -*-
"""
模型配置键定义
定义各意图对应的环境变量键名映射。
"""

from dataclasses import dataclass
from .constants import (
    MIDSCENE_MODEL_NAME,
    MIDSCENE_MODEL_SOCKS_PROXY,
    MIDSCENE_MODEL_HTTP_PROXY,
    MIDSCENE_MODEL_BASE_URL,
    MIDSCENE_MODEL_API_KEY,
    MIDSCENE_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_MODEL_FAMILY,
    MIDSCENE_MODEL_TIMEOUT,
    MIDSCENE_MODEL_TEMPERATURE,
    MIDSCENE_INSIGHT_MODEL_NAME,
    MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY,
    MIDSCENE_INSIGHT_MODEL_HTTP_PROXY,
    MIDSCENE_INSIGHT_MODEL_BASE_URL,
    MIDSCENE_INSIGHT_MODEL_API_KEY,
    MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_INSIGHT_MODEL_TIMEOUT,
    MIDSCENE_INSIGHT_MODEL_TEMPERATURE,
    MIDSCENE_PLANNING_MODEL_NAME,
    MIDSCENE_PLANNING_MODEL_SOCKS_PROXY,
    MIDSCENE_PLANNING_MODEL_HTTP_PROXY,
    MIDSCENE_PLANNING_MODEL_BASE_URL,
    MIDSCENE_PLANNING_MODEL_API_KEY,
    MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_PLANNING_MODEL_TIMEOUT,
    MIDSCENE_PLANNING_MODEL_TEMPERATURE,
    OPENAI_API_KEY,
    OPENAI_BASE_URL,
)


@dataclass
class ModelConfigKeys:
    """模型配置键定义"""
    model_name: str
    socks_proxy: str
    http_proxy: str
    openai_base_url: str
    openai_api_key: str
    openai_extra_config: str
    model_family: str
    timeout: str
    temperature: str


# Insight 模型配置键
INSIGHT_MODEL_CONFIG_KEYS = ModelConfigKeys(
    model_name=MIDSCENE_INSIGHT_MODEL_NAME,
    socks_proxy=MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY,
    http_proxy=MIDSCENE_INSIGHT_MODEL_HTTP_PROXY,
    openai_base_url=MIDSCENE_INSIGHT_MODEL_BASE_URL,
    openai_api_key=MIDSCENE_INSIGHT_MODEL_API_KEY,
    openai_extra_config=MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON,
    model_family="THERE_IS_NO_MODEL_FAMILY_FOR_INSIGHT",
    timeout=MIDSCENE_INSIGHT_MODEL_TIMEOUT,
    temperature=MIDSCENE_INSIGHT_MODEL_TEMPERATURE,
)

# Planning 模型配置键
PLANNING_MODEL_CONFIG_KEYS = ModelConfigKeys(
    model_name=MIDSCENE_PLANNING_MODEL_NAME,
    socks_proxy=MIDSCENE_PLANNING_MODEL_SOCKS_PROXY,
    http_proxy=MIDSCENE_PLANNING_MODEL_HTTP_PROXY,
    openai_base_url=MIDSCENE_PLANNING_MODEL_BASE_URL,
    openai_api_key=MIDSCENE_PLANNING_MODEL_API_KEY,
    openai_extra_config=MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON,
    model_family="THERE_IS_NO_MODEL_FAMILY_FOR_PLANNING",
    timeout=MIDSCENE_PLANNING_MODEL_TIMEOUT,
    temperature=MIDSCENE_PLANNING_MODEL_TEMPERATURE,
)

# 默认模型配置键
DEFAULT_MODEL_CONFIG_KEYS = ModelConfigKeys(
    model_name=MIDSCENE_MODEL_NAME,
    socks_proxy=MIDSCENE_MODEL_SOCKS_PROXY,
    http_proxy=MIDSCENE_MODEL_HTTP_PROXY,
    openai_base_url=MIDSCENE_MODEL_BASE_URL,
    openai_api_key=MIDSCENE_MODEL_API_KEY,
    openai_extra_config=MIDSCENE_MODEL_INIT_CONFIG_JSON,
    model_family=MIDSCENE_MODEL_FAMILY,
    timeout=MIDSCENE_MODEL_TIMEOUT,
    temperature=MIDSCENE_MODEL_TEMPERATURE,
)

# 意图到配置键的映射
INTENT_KEYS_MAP = {
    "insight": INSIGHT_MODEL_CONFIG_KEYS,
    "planning": PLANNING_MODEL_CONFIG_KEYS,
    "default": DEFAULT_MODEL_CONFIG_KEYS,
}
