# -*- coding: utf-8 -*-
"""
环境变量常量定义
定义所有 Midscene 使用的环境变量键名。
"""

# 基础配置键
MIDSCENE_MODEL_INIT_CONFIG_JSON = "MIDSCENE_MODEL_INIT_CONFIG_JSON"
MIDSCENE_MODEL_NAME = "MIDSCENE_MODEL_NAME"
MIDSCENE_DEBUG_MODEL_PROFILE = "MIDSCENE_DEBUG_MODEL_PROFILE"
MIDSCENE_DEBUG_MODEL_RESPONSE = "MIDSCENE_DEBUG_MODEL_RESPONSE"
MIDSCENE_DANGEROUSLY_PRINT_ALL_CONFIG = "MIDSCENE_DANGEROUSLY_PRINT_ALL_CONFIG"
MIDSCENE_DEBUG_MODE = "MIDSCENE_DEBUG_MODE"
MIDSCENE_FORCE_DEEP_THINK = "MIDSCENE_FORCE_DEEP_THINK"

# 可观测性
MIDSCENE_LANGSMITH_DEBUG = "MIDSCENE_LANGSMITH_DEBUG"
MIDSCENE_LANGFUSE_DEBUG = "MIDSCENE_LANGFUSE_DEBUG"

# 代理设置
MIDSCENE_MODEL_SOCKS_PROXY = "MIDSCENE_MODEL_SOCKS_PROXY"
MIDSCENE_MODEL_HTTP_PROXY = "MIDSCENE_MODEL_HTTP_PROXY"

# 模型 API 配置（新版）
MIDSCENE_MODEL_API_KEY = "MIDSCENE_MODEL_API_KEY"
MIDSCENE_MODEL_BASE_URL = "MIDSCENE_MODEL_BASE_URL"
MIDSCENE_MODEL_MAX_TOKENS = "MIDSCENE_MODEL_MAX_TOKENS"
MIDSCENE_MODEL_TIMEOUT = "MIDSCENE_MODEL_TIMEOUT"
MIDSCENE_MODEL_TEMPERATURE = "MIDSCENE_MODEL_TEMPERATURE"

# 兼容旧版环境变量
OPENAI_API_KEY = "OPENAI_API_KEY"
OPENAI_BASE_URL = "OPENAI_BASE_URL"
OPENAI_MAX_TOKENS = "OPENAI_MAX_TOKENS"

# 缓存设置
MIDSCENE_CACHE = "MIDSCENE_CACHE"
MIDSCENE_CACHE_MAX_FILENAME_LENGTH = "MIDSCENE_CACHE_MAX_FILENAME_LENGTH"

# VL 模型设置
MIDSCENE_USE_VLM_UI_TARS = "MIDSCENE_USE_VLM_UI_TARS"
MIDSCENE_USE_QWEN_VL = "MIDSCENE_USE_QWEN_VL"
MIDSCENE_USE_QWEN3_VL = "MIDSCENE_USE_QWEN3_VL"
MIDSCENE_USE_DOUBAO_VISION = "MIDSCENE_USE_DOUBAO_VISION"
MIDSCENE_USE_GEMINI = "MIDSCENE_USE_GEMINI"
MIDSCENE_USE_VL_MODEL = "MIDSCENE_USE_VL_MODEL"
MIDSCENE_MODEL_FAMILY = "MIDSCENE_MODEL_FAMILY"

# 其他设置
MIDSCENE_REPLANNING_CYCLE_LIMIT = "MIDSCENE_REPLANNING_CYCLE_LIMIT"
MIDSCENE_RUN_DIR = "MIDSCENE_RUN_DIR"
MIDSCENE_PREFERRED_LANGUAGE = "MIDSCENE_PREFERRED_LANGUAGE"
MIDSCENE_REPORT_TAG_NAME = "MIDSCENE_REPORT_TAG_NAME"
MATCH_BY_POSITION = "MATCH_BY_POSITION"

# Insight 模型配置
MIDSCENE_INSIGHT_MODEL_NAME = "MIDSCENE_INSIGHT_MODEL_NAME"
MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY = "MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY"
MIDSCENE_INSIGHT_MODEL_HTTP_PROXY = "MIDSCENE_INSIGHT_MODEL_HTTP_PROXY"
MIDSCENE_INSIGHT_MODEL_BASE_URL = "MIDSCENE_INSIGHT_MODEL_BASE_URL"
MIDSCENE_INSIGHT_MODEL_API_KEY = "MIDSCENE_INSIGHT_MODEL_API_KEY"
MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON = "MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON"
MIDSCENE_INSIGHT_MODEL_TIMEOUT = "MIDSCENE_INSIGHT_MODEL_TIMEOUT"
MIDSCENE_INSIGHT_MODEL_TEMPERATURE = "MIDSCENE_INSIGHT_MODEL_TEMPERATURE"

# Planning 模型配置
MIDSCENE_PLANNING_MODEL_NAME = "MIDSCENE_PLANNING_MODEL_NAME"
MIDSCENE_PLANNING_MODEL_SOCKS_PROXY = "MIDSCENE_PLANNING_MODEL_SOCKS_PROXY"
MIDSCENE_PLANNING_MODEL_HTTP_PROXY = "MIDSCENE_PLANNING_MODEL_HTTP_PROXY"
MIDSCENE_PLANNING_MODEL_BASE_URL = "MIDSCENE_PLANNING_MODEL_BASE_URL"
MIDSCENE_PLANNING_MODEL_API_KEY = "MIDSCENE_PLANNING_MODEL_API_KEY"
MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON = "MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON"
MIDSCENE_PLANNING_MODEL_TIMEOUT = "MIDSCENE_PLANNING_MODEL_TIMEOUT"
MIDSCENE_PLANNING_MODEL_TEMPERATURE = "MIDSCENE_PLANNING_MODEL_TEMPERATURE"

# VL 模式类型
VL_MODE_RAW_VALID_VALUES = [
    "doubao-vision",
    "gemini",
    "qwen2.5-vl",
    "qwen3-vl",
    "vlm-ui-tars",
    "vlm-ui-tars-doubao",
    "vlm-ui-tars-doubao-1.5",
]

# 模型家族值
MODEL_FAMILY_VALUES = VL_MODE_RAW_VALID_VALUES.copy()

# 基础环境变量键（不能被 overrideAIConfig 覆盖）
BASIC_ENV_KEYS = [
    MIDSCENE_DEBUG_MODE,
    MIDSCENE_DEBUG_MODEL_PROFILE,
    MIDSCENE_DEBUG_MODEL_RESPONSE,
    MIDSCENE_RUN_DIR,
]

# 布尔类型环境变量键
BOOLEAN_ENV_KEYS = [
    MIDSCENE_CACHE,
    MIDSCENE_FORCE_DEEP_THINK,
    MIDSCENE_LANGSMITH_DEBUG,
    MIDSCENE_LANGFUSE_DEBUG,
]

# 数字类型环境变量键
NUMBER_ENV_KEYS = [
    MIDSCENE_CACHE_MAX_FILENAME_LENGTH,
    MIDSCENE_REPLANNING_CYCLE_LIMIT,
]

# 字符串类型环境变量键
STRING_ENV_KEYS = [
    MIDSCENE_MODEL_MAX_TOKENS,
    OPENAI_MAX_TOKENS,
    MIDSCENE_REPORT_TAG_NAME,
    MIDSCENE_PREFERRED_LANGUAGE,
    MATCH_BY_POSITION,
]

# 全局环境变量键
GLOBAL_ENV_KEYS = BOOLEAN_ENV_KEYS + NUMBER_ENV_KEYS + STRING_ENV_KEYS

# 模型相关环境变量键
MODEL_ENV_KEYS = [
    # 模型默认配置
    MIDSCENE_MODEL_NAME,
    MIDSCENE_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_MODEL_API_KEY,
    MIDSCENE_MODEL_BASE_URL,
    MIDSCENE_MODEL_SOCKS_PROXY,
    MIDSCENE_MODEL_HTTP_PROXY,
    MIDSCENE_MODEL_TIMEOUT,
    MIDSCENE_MODEL_TEMPERATURE,
    MIDSCENE_USE_VLM_UI_TARS,
    MIDSCENE_USE_QWEN_VL,
    MIDSCENE_USE_QWEN3_VL,
    MIDSCENE_USE_DOUBAO_VISION,
    MIDSCENE_USE_GEMINI,
    MIDSCENE_USE_VL_MODEL,
    # 兼容旧版
    OPENAI_API_KEY,
    OPENAI_BASE_URL,
    # Insight 模型
    MIDSCENE_INSIGHT_MODEL_NAME,
    MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY,
    MIDSCENE_INSIGHT_MODEL_HTTP_PROXY,
    MIDSCENE_INSIGHT_MODEL_BASE_URL,
    MIDSCENE_INSIGHT_MODEL_API_KEY,
    MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_INSIGHT_MODEL_TIMEOUT,
    MIDSCENE_INSIGHT_MODEL_TEMPERATURE,
    # Planning 模型
    MIDSCENE_PLANNING_MODEL_NAME,
    MIDSCENE_PLANNING_MODEL_SOCKS_PROXY,
    MIDSCENE_PLANNING_MODEL_HTTP_PROXY,
    MIDSCENE_PLANNING_MODEL_BASE_URL,
    MIDSCENE_PLANNING_MODEL_API_KEY,
    MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_PLANNING_MODEL_TIMEOUT,
    MIDSCENE_PLANNING_MODEL_TEMPERATURE,
    MIDSCENE_MODEL_FAMILY,
]

# 所有环境变量键
ALL_ENV_KEYS = BASIC_ENV_KEYS + GLOBAL_ENV_KEYS + MODEL_ENV_KEYS
