"""
环境变量类型定义

对应TypeScript源码: packages/shared/src/env/types.ts
"""

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Literal, Optional, TypedDict, Union

# ============ 配置键常量 ============

# 模型初始化配置
MIDSCENE_MODEL_INIT_CONFIG_JSON = "MIDSCENE_MODEL_INIT_CONFIG_JSON"
MIDSCENE_MODEL_NAME = "MIDSCENE_MODEL_NAME"
MIDSCENE_DEBUG_MODEL_PROFILE = "MIDSCENE_DEBUG_MODEL_PROFILE"
MIDSCENE_DEBUG_MODEL_RESPONSE = "MIDSCENE_DEBUG_MODEL_RESPONSE"
MIDSCENE_DANGEROUSLY_PRINT_ALL_CONFIG = "MIDSCENE_DANGEROUSLY_PRINT_ALL_CONFIG"
MIDSCENE_DEBUG_MODE = "MIDSCENE_DEBUG_MODE"

# MCP相关配置
MIDSCENE_MCP_USE_PUPPETEER_MODE = "MIDSCENE_MCP_USE_PUPPETEER_MODE"
MIDSCENE_MCP_CHROME_PATH = "MIDSCENE_MCP_CHROME_PATH"
MIDSCENE_MCP_ANDROID_MODE = "MIDSCENE_MCP_ANDROID_MODE"
DOCKER_CONTAINER = "DOCKER_CONTAINER"

# 深度思考
MIDSCENE_FORCE_DEEP_THINK = "MIDSCENE_FORCE_DEEP_THINK"

# 可观测性
MIDSCENE_LANGSMITH_DEBUG = "MIDSCENE_LANGSMITH_DEBUG"
MIDSCENE_LANGFUSE_DEBUG = "MIDSCENE_LANGFUSE_DEBUG"

# 代理配置
MIDSCENE_MODEL_SOCKS_PROXY = "MIDSCENE_MODEL_SOCKS_PROXY"
MIDSCENE_MODEL_HTTP_PROXY = "MIDSCENE_MODEL_HTTP_PROXY"

# 新的主要配置名称（公共API）
MIDSCENE_MODEL_API_KEY = "MIDSCENE_MODEL_API_KEY"
MIDSCENE_MODEL_BASE_URL = "MIDSCENE_MODEL_BASE_URL"
MIDSCENE_MODEL_MAX_TOKENS = "MIDSCENE_MODEL_MAX_TOKENS"
MIDSCENE_MODEL_TIMEOUT = "MIDSCENE_MODEL_TIMEOUT"
MIDSCENE_MODEL_TEMPERATURE = "MIDSCENE_MODEL_TEMPERATURE"

# 旧版配置（为了向后兼容）
OPENAI_API_KEY = "OPENAI_API_KEY"
OPENAI_BASE_URL = "OPENAI_BASE_URL"
MIDSCENE_OPENAI_INIT_CONFIG_JSON = "MIDSCENE_OPENAI_INIT_CONFIG_JSON"
MIDSCENE_OPENAI_HTTP_PROXY = "MIDSCENE_OPENAI_HTTP_PROXY"
MIDSCENE_OPENAI_SOCKS_PROXY = "MIDSCENE_OPENAI_SOCKS_PROXY"
OPENAI_MAX_TOKENS = "OPENAI_MAX_TOKENS"

# Android配置
MIDSCENE_ADB_PATH = "MIDSCENE_ADB_PATH"
MIDSCENE_ADB_REMOTE_HOST = "MIDSCENE_ADB_REMOTE_HOST"
MIDSCENE_ADB_REMOTE_PORT = "MIDSCENE_ADB_REMOTE_PORT"
MIDSCENE_ANDROID_IME_STRATEGY = "MIDSCENE_ANDROID_IME_STRATEGY"

# iOS配置
MIDSCENE_IOS_DEVICE_UDID = "MIDSCENE_IOS_DEVICE_UDID"
MIDSCENE_IOS_SIMULATOR_UDID = "MIDSCENE_IOS_SIMULATOR_UDID"

# 其他配置
MIDSCENE_CACHE = "MIDSCENE_CACHE"
MIDSCENE_USE_VLM_UI_TARS = "MIDSCENE_USE_VLM_UI_TARS"
MIDSCENE_USE_QWEN_VL = "MIDSCENE_USE_QWEN_VL"
MIDSCENE_USE_QWEN3_VL = "MIDSCENE_USE_QWEN3_VL"
MIDSCENE_USE_DOUBAO_VISION = "MIDSCENE_USE_DOUBAO_VISION"
MIDSCENE_USE_GEMINI = "MIDSCENE_USE_GEMINI"
MIDSCENE_USE_VL_MODEL = "MIDSCENE_USE_VL_MODEL"
MATCH_BY_POSITION = "MATCH_BY_POSITION"
MIDSCENE_REPORT_TAG_NAME = "MIDSCENE_REPORT_TAG_NAME"
MIDSCENE_PREFERRED_LANGUAGE = "MIDSCENE_PREFERRED_LANGUAGE"
MIDSCENE_CACHE_MAX_FILENAME_LENGTH = "MIDSCENE_CACHE_MAX_FILENAME_LENGTH"
MIDSCENE_REPLANNING_CYCLE_LIMIT = "MIDSCENE_REPLANNING_CYCLE_LIMIT"
MIDSCENE_RUN_DIR = "MIDSCENE_RUN_DIR"

# Insight模型配置
MIDSCENE_INSIGHT_MODEL_NAME = "MIDSCENE_INSIGHT_MODEL_NAME"
MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY = "MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY"
MIDSCENE_INSIGHT_MODEL_HTTP_PROXY = "MIDSCENE_INSIGHT_MODEL_HTTP_PROXY"
MIDSCENE_INSIGHT_MODEL_BASE_URL = "MIDSCENE_INSIGHT_MODEL_BASE_URL"
MIDSCENE_INSIGHT_MODEL_API_KEY = "MIDSCENE_INSIGHT_MODEL_API_KEY"
MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON = "MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON"
MIDSCENE_INSIGHT_MODEL_TIMEOUT = "MIDSCENE_INSIGHT_MODEL_TIMEOUT"
MIDSCENE_INSIGHT_MODEL_TEMPERATURE = "MIDSCENE_INSIGHT_MODEL_TEMPERATURE"

# Planning模型配置
MIDSCENE_PLANNING_MODEL_NAME = "MIDSCENE_PLANNING_MODEL_NAME"
MIDSCENE_PLANNING_MODEL_SOCKS_PROXY = "MIDSCENE_PLANNING_MODEL_SOCKS_PROXY"
MIDSCENE_PLANNING_MODEL_HTTP_PROXY = "MIDSCENE_PLANNING_MODEL_HTTP_PROXY"
MIDSCENE_PLANNING_MODEL_BASE_URL = "MIDSCENE_PLANNING_MODEL_BASE_URL"
MIDSCENE_PLANNING_MODEL_API_KEY = "MIDSCENE_PLANNING_MODEL_API_KEY"
MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON = "MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON"
MIDSCENE_PLANNING_MODEL_TIMEOUT = "MIDSCENE_PLANNING_MODEL_TIMEOUT"
MIDSCENE_PLANNING_MODEL_TEMPERATURE = "MIDSCENE_PLANNING_MODEL_TEMPERATURE"
MIDSCENE_MODEL_FAMILY = "MIDSCENE_MODEL_FAMILY"

# ============ 类型定义 ============

# VL模式类型
TVlModeValues = Literal[
    "qwen2.5-vl",
    "qwen3-vl",
    "doubao-vision",
    "gemini",
    "vlm-ui-tars",
    "vlm-ui-tars-doubao",
    "vlm-ui-tars-doubao-1.5",
]

TVlModeTypes = Literal[
    "qwen2.5-vl",
    "qwen3-vl", 
    "doubao-vision",
    "gemini",
    "vlm-ui-tars",
]

VL_MODE_RAW_VALID_VALUES: List[str] = [
    "doubao-vision",
    "gemini",
    "qwen2.5-vl",
    "qwen3-vl",
    "vlm-ui-tars",
    "vlm-ui-tars-doubao",
    "vlm-ui-tars-doubao-1.5",
]

# 模型家族值
TModelFamily = TVlModeValues
MODEL_FAMILY_VALUES = VL_MODE_RAW_VALID_VALUES.copy()

# Intent类型
TIntent = Literal["insight", "planning", "default"]

# 模型配置字典类型
TModelConfig = Dict[str, Union[str, int]]

# UI-TARS模型版本
class UITarsModelVersion:
    V1_0 = "1.0"
    V1_5 = "1.5"
    DOUBAO_1_5_15B = "doubao-1.5-15B"
    DOUBAO_1_5_20B = "doubao-1.5-20B"


# OpenAI客户端创建回调类型
CreateOpenAIClientFn = Callable[[Any, Dict[str, Any]], Any]


@dataclass
class IModelConfig:
    """模型配置接口
    
    定义了调用AI模型所需的所有配置参数
    """
    # 模型名称
    model_name: str
    
    # 模型描述
    model_description: str = ""
    
    # Intent类型
    intent: str = "default"  # TIntent
    
    # 代理配置
    socks_proxy: Optional[str] = None
    http_proxy: Optional[str] = None
    
    # OpenAI配置
    openai_base_url: Optional[str] = None
    openai_api_key: Optional[str] = None
    openai_extra_config: Optional[Dict[str, Any]] = None
    
    # 超时配置（毫秒）
    timeout: Optional[int] = None
    
    # 温度参数
    temperature: Optional[float] = None
    
    # VL模式相关
    vl_mode_raw: Optional[str] = None
    vl_mode: Optional[str] = None  # TVlModeTypes
    ui_tars_model_version: Optional[str] = None
    
    # 自定义OpenAI客户端工厂
    create_openai_client: Optional[CreateOpenAIClientFn] = None


# 布尔类型环境变量
BOOLEAN_ENV_KEYS = [
    MIDSCENE_CACHE,
    MIDSCENE_FORCE_DEEP_THINK,
    MIDSCENE_MCP_USE_PUPPETEER_MODE,
    MIDSCENE_MCP_ANDROID_MODE,
    MIDSCENE_LANGSMITH_DEBUG,
    MIDSCENE_LANGFUSE_DEBUG,
]

# 数字类型环境变量
NUMBER_ENV_KEYS = [
    MIDSCENE_CACHE_MAX_FILENAME_LENGTH,
    MIDSCENE_REPLANNING_CYCLE_LIMIT,
]

# 字符串类型环境变量
STRING_ENV_KEYS = [
    MIDSCENE_MODEL_MAX_TOKENS,
    OPENAI_MAX_TOKENS,
    MIDSCENE_ADB_PATH,
    MIDSCENE_ADB_REMOTE_HOST,
    MIDSCENE_ADB_REMOTE_PORT,
    MIDSCENE_ANDROID_IME_STRATEGY,
    MIDSCENE_IOS_DEVICE_UDID,
    MIDSCENE_IOS_SIMULATOR_UDID,
    MIDSCENE_REPORT_TAG_NAME,
    MIDSCENE_PREFERRED_LANGUAGE,
    MATCH_BY_POSITION,
    MIDSCENE_MCP_CHROME_PATH,
    DOCKER_CONTAINER,
]

# 基本环境变量
BASIC_ENV_KEYS = [
    MIDSCENE_DEBUG_MODE,
    MIDSCENE_DEBUG_MODEL_PROFILE,
    MIDSCENE_DEBUG_MODEL_RESPONSE,
    MIDSCENE_RUN_DIR,
]

# 全局环境变量
GLOBAL_ENV_KEYS = BOOLEAN_ENV_KEYS + NUMBER_ENV_KEYS + STRING_ENV_KEYS

# 模型相关环境变量
MODEL_ENV_KEYS = [
    # 默认模型
    MIDSCENE_MODEL_NAME,
    MIDSCENE_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_MODEL_API_KEY,
    MIDSCENE_MODEL_BASE_URL,
    MIDSCENE_MODEL_SOCKS_PROXY,
    MIDSCENE_MODEL_HTTP_PROXY,
    MIDSCENE_MODEL_TIMEOUT,
    MIDSCENE_MODEL_TEMPERATURE,
    MIDSCENE_USE_VLM_UI_TARS,
    MIDSCENE_USE_QWEN_VL,
    MIDSCENE_USE_QWEN3_VL,
    MIDSCENE_USE_DOUBAO_VISION,
    MIDSCENE_USE_GEMINI,
    MIDSCENE_USE_VL_MODEL,
    # 旧版配置
    OPENAI_API_KEY,
    OPENAI_BASE_URL,
    MIDSCENE_OPENAI_INIT_CONFIG_JSON,
    MIDSCENE_OPENAI_HTTP_PROXY,
    MIDSCENE_OPENAI_SOCKS_PROXY,
    # Insight模型
    MIDSCENE_INSIGHT_MODEL_NAME,
    MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY,
    MIDSCENE_INSIGHT_MODEL_HTTP_PROXY,
    MIDSCENE_INSIGHT_MODEL_BASE_URL,
    MIDSCENE_INSIGHT_MODEL_API_KEY,
    MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_INSIGHT_MODEL_TIMEOUT,
    MIDSCENE_INSIGHT_MODEL_TEMPERATURE,
    # Planning模型
    MIDSCENE_PLANNING_MODEL_NAME,
    MIDSCENE_PLANNING_MODEL_SOCKS_PROXY,
    MIDSCENE_PLANNING_MODEL_HTTP_PROXY,
    MIDSCENE_PLANNING_MODEL_BASE_URL,
    MIDSCENE_PLANNING_MODEL_API_KEY,
    MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_PLANNING_MODEL_TIMEOUT,
    MIDSCENE_PLANNING_MODEL_TEMPERATURE,
    MIDSCENE_MODEL_FAMILY,
]

# 所有环境变量
ALL_ENV_KEYS = [MIDSCENE_DANGEROUSLY_PRINT_ALL_CONFIG] + BASIC_ENV_KEYS + GLOBAL_ENV_KEYS + MODEL_ENV_KEYS
