"""
环境变量类型定义

从 packages/shared/src/env/types.ts 迁移
注意：已删除所有废弃的环境变量（如OPENAI_API_KEY等）
"""

from enum import Enum
from typing import Any, Callable, Literal, Optional

from pydantic import BaseModel


# ========== 环境变量名常量 ==========

# 模型相关
MIDSCENE_MODEL_NAME = "MIDSCENE_MODEL_NAME"
MIDSCENE_MODEL_API_KEY = "MIDSCENE_MODEL_API_KEY"
MIDSCENE_MODEL_BASE_URL = "MIDSCENE_MODEL_BASE_URL"
MIDSCENE_MODEL_SOCKS_PROXY = "MIDSCENE_MODEL_SOCKS_PROXY"
MIDSCENE_MODEL_HTTP_PROXY = "MIDSCENE_MODEL_HTTP_PROXY"
MIDSCENE_MODEL_MAX_TOKENS = "MIDSCENE_MODEL_MAX_TOKENS"
MIDSCENE_MODEL_TIMEOUT = "MIDSCENE_MODEL_TIMEOUT"
MIDSCENE_MODEL_TEMPERATURE = "MIDSCENE_MODEL_TEMPERATURE"
MIDSCENE_MODEL_FAMILY = "MIDSCENE_MODEL_FAMILY"
MIDSCENE_MODEL_INIT_CONFIG_JSON = "MIDSCENE_MODEL_INIT_CONFIG_JSON"

# 调试相关
MIDSCENE_DEBUG_MODE = "MIDSCENE_DEBUG_MODE"
MIDSCENE_DEBUG_MODEL_PROFILE = "MIDSCENE_DEBUG_MODEL_PROFILE"
MIDSCENE_DEBUG_MODEL_RESPONSE = "MIDSCENE_DEBUG_MODEL_RESPONSE"

# 运行时配置
MIDSCENE_RUN_DIR = "MIDSCENE_RUN_DIR"
MIDSCENE_CACHE = "MIDSCENE_CACHE"
MIDSCENE_FORCE_DEEP_THINK = "MIDSCENE_FORCE_DEEP_THINK"
MIDSCENE_PREFERRED_LANGUAGE = "MIDSCENE_PREFERRED_LANGUAGE"
MIDSCENE_REPLANNING_CYCLE_LIMIT = "MIDSCENE_REPLANNING_CYCLE_LIMIT"
MIDSCENE_CACHE_MAX_FILENAME_LENGTH = "MIDSCENE_CACHE_MAX_FILENAME_LENGTH"
MIDSCENE_REPORT_TAG_NAME = "MIDSCENE_REPORT_TAG_NAME"

# Insight模型配置
MIDSCENE_INSIGHT_MODEL_NAME = "MIDSCENE_INSIGHT_MODEL_NAME"
MIDSCENE_INSIGHT_MODEL_API_KEY = "MIDSCENE_INSIGHT_MODEL_API_KEY"
MIDSCENE_INSIGHT_MODEL_BASE_URL = "MIDSCENE_INSIGHT_MODEL_BASE_URL"
MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY = "MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY"
MIDSCENE_INSIGHT_MODEL_HTTP_PROXY = "MIDSCENE_INSIGHT_MODEL_HTTP_PROXY"
MIDSCENE_INSIGHT_MODEL_TIMEOUT = "MIDSCENE_INSIGHT_MODEL_TIMEOUT"
MIDSCENE_INSIGHT_MODEL_TEMPERATURE = "MIDSCENE_INSIGHT_MODEL_TEMPERATURE"
MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON = "MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON"

# Planning模型配置
MIDSCENE_PLANNING_MODEL_NAME = "MIDSCENE_PLANNING_MODEL_NAME"
MIDSCENE_PLANNING_MODEL_API_KEY = "MIDSCENE_PLANNING_MODEL_API_KEY"
MIDSCENE_PLANNING_MODEL_BASE_URL = "MIDSCENE_PLANNING_MODEL_BASE_URL"
MIDSCENE_PLANNING_MODEL_SOCKS_PROXY = "MIDSCENE_PLANNING_MODEL_SOCKS_PROXY"
MIDSCENE_PLANNING_MODEL_HTTP_PROXY = "MIDSCENE_PLANNING_MODEL_HTTP_PROXY"
MIDSCENE_PLANNING_MODEL_TIMEOUT = "MIDSCENE_PLANNING_MODEL_TIMEOUT"
MIDSCENE_PLANNING_MODEL_TEMPERATURE = "MIDSCENE_PLANNING_MODEL_TEMPERATURE"
MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON = "MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON"

# 可观测性
MIDSCENE_LANGSMITH_DEBUG = "MIDSCENE_LANGSMITH_DEBUG"
MIDSCENE_LANGFUSE_DEBUG = "MIDSCENE_LANGFUSE_DEBUG"

# Android相关
MIDSCENE_ADB_PATH = "MIDSCENE_ADB_PATH"
MIDSCENE_ADB_REMOTE_HOST = "MIDSCENE_ADB_REMOTE_HOST"
MIDSCENE_ADB_REMOTE_PORT = "MIDSCENE_ADB_REMOTE_PORT"
MIDSCENE_ANDROID_IME_STRATEGY = "MIDSCENE_ANDROID_IME_STRATEGY"

# iOS相关
MIDSCENE_IOS_DEVICE_UDID = "MIDSCENE_IOS_DEVICE_UDID"
MIDSCENE_IOS_SIMULATOR_UDID = "MIDSCENE_IOS_SIMULATOR_UDID"

# 其他
DOCKER_CONTAINER = "DOCKER_CONTAINER"
MATCH_BY_POSITION = "MATCH_BY_POSITION"


# ========== 类型定义 ==========

# VL模式类型
VLModeType = Literal[
    "qwen2.5-vl",
    "qwen3-vl",
    "doubao-vision",
    "gemini",
]

# VL模式原始值 (包含UI-TARS变体，但按用户要求已移除)
VLModeRawValue = Literal[
    "qwen2.5-vl",
    "qwen3-vl",
    "doubao-vision",
    "gemini",
]

# 模型意图类型
ModelIntent = Literal["insight", "planning", "default"]

# 模型家族值
MODEL_FAMILY_VALUES: list[str] = [
    "qwen2.5-vl",
    "qwen3-vl",
    "doubao-vision",
    "gemini",
]


# ========== 环境变量分类 ==========

# 基础环境变量（不能被覆盖）
BASIC_ENV_KEYS = [
    MIDSCENE_DEBUG_MODE,
    MIDSCENE_DEBUG_MODEL_PROFILE,
    MIDSCENE_DEBUG_MODEL_RESPONSE,
    MIDSCENE_RUN_DIR,
]

# 布尔类型环境变量
BOOLEAN_ENV_KEYS = [
    MIDSCENE_CACHE,
    MIDSCENE_FORCE_DEEP_THINK,
    MIDSCENE_LANGSMITH_DEBUG,
    MIDSCENE_LANGFUSE_DEBUG,
]

# 数字类型环境变量
NUMBER_ENV_KEYS = [
    MIDSCENE_CACHE_MAX_FILENAME_LENGTH,
    MIDSCENE_REPLANNING_CYCLE_LIMIT,
]

# 字符串类型环境变量
STRING_ENV_KEYS = [
    MIDSCENE_MODEL_MAX_TOKENS,
    MIDSCENE_ADB_PATH,
    MIDSCENE_ADB_REMOTE_HOST,
    MIDSCENE_ADB_REMOTE_PORT,
    MIDSCENE_ANDROID_IME_STRATEGY,
    MIDSCENE_IOS_DEVICE_UDID,
    MIDSCENE_IOS_SIMULATOR_UDID,
    MIDSCENE_REPORT_TAG_NAME,
    MIDSCENE_PREFERRED_LANGUAGE,
    MATCH_BY_POSITION,
    DOCKER_CONTAINER,
]

# 全局环境变量（可以被overrideAIConfig覆盖）
GLOBAL_ENV_KEYS = BOOLEAN_ENV_KEYS + NUMBER_ENV_KEYS + STRING_ENV_KEYS

# 模型相关环境变量
MODEL_ENV_KEYS = [
    # 默认模型
    MIDSCENE_MODEL_NAME,
    MIDSCENE_MODEL_INIT_CONFIG_JSON,
    MIDSCENE_MODEL_API_KEY,
    MIDSCENE_MODEL_BASE_URL,
    MIDSCENE_MODEL_SOCKS_PROXY,
    MIDSCENE_MODEL_HTTP_PROXY,
    MIDSCENE_MODEL_TIMEOUT,
    MIDSCENE_MODEL_TEMPERATURE,
    MIDSCENE_MODEL_FAMILY,
    # Insight模型
    MIDSCENE_INSIGHT_MODEL_NAME,
    MIDSCENE_INSIGHT_MODEL_API_KEY,
    MIDSCENE_INSIGHT_MODEL_BASE_URL,
    MIDSCENE_INSIGHT_MODEL_SOCKS_PROXY,
    MIDSCENE_INSIGHT_MODEL_HTTP_PROXY,
    MIDSCENE_INSIGHT_MODEL_TIMEOUT,
    MIDSCENE_INSIGHT_MODEL_TEMPERATURE,
    MIDSCENE_INSIGHT_MODEL_INIT_CONFIG_JSON,
    # Planning模型
    MIDSCENE_PLANNING_MODEL_NAME,
    MIDSCENE_PLANNING_MODEL_API_KEY,
    MIDSCENE_PLANNING_MODEL_BASE_URL,
    MIDSCENE_PLANNING_MODEL_SOCKS_PROXY,
    MIDSCENE_PLANNING_MODEL_HTTP_PROXY,
    MIDSCENE_PLANNING_MODEL_TIMEOUT,
    MIDSCENE_PLANNING_MODEL_TEMPERATURE,
    MIDSCENE_PLANNING_MODEL_INIT_CONFIG_JSON,
]

# 所有环境变量
ALL_ENV_KEYS = BASIC_ENV_KEYS + GLOBAL_ENV_KEYS + MODEL_ENV_KEYS


# ========== 数据模型 ==========

class ModelConfig(BaseModel):
    """模型配置"""
    
    # 代理设置
    socks_proxy: Optional[str] = None
    http_proxy: Optional[str] = None
    
    # 模型名称
    model_name: str
    
    # OpenAI配置
    openai_base_url: Optional[str] = None
    openai_api_key: Optional[str] = None
    openai_extra_config: Optional[dict[str, Any]] = None
    
    # API调用超时（毫秒）
    timeout: Optional[int] = None
    
    # 采样温度
    temperature: Optional[float] = None
    
    # VL模式
    vl_mode_raw: Optional[str] = None
    vl_mode: Optional[VLModeType] = None
    
    # 模型描述
    model_description: str = ""
    
    # 意图
    intent: ModelIntent = "default"
    
    # 自定义OpenAI客户端工厂函数
    create_openai_client: Optional[Callable] = None
    
    class Config:
        arbitrary_types_allowed = True
