"""
常量定义
"""

# 文本尺寸阈值
TEXT_SIZE_THRESHOLD = 9
TEXT_MAX_SIZE = 40

# 容器最小尺寸
CONTAINER_MINI_HEIGHT = 3
CONTAINER_MINI_WIDTH = 3

# 服务器端口
PLAYGROUND_SERVER_PORT = 5800
SCRCPY_SERVER_PORT = 5700

# WebDriver常量
WEBDRIVER_ELEMENT_ID_KEY = "element-6066-11e4-a52e-4f735466cecf"
DEFAULT_WDA_PORT = 8100

# 默认超时设置
DEFAULT_WAIT_FOR_NAVIGATION_TIMEOUT = 5000
DEFAULT_WAIT_FOR_NETWORK_IDLE_TIMEOUT = 2000
DEFAULT_WAIT_FOR_NETWORK_IDLE_TIME = 300
DEFAULT_WAIT_FOR_NETWORK_IDLE_CONCURRENCY = 2
